version = 1
exclude_patterns = [
 "bad/**",
 "install.sh",
 "utils/**"
]
test_patterns = [
  "setup.py",
  "good/**"
]

[[analyzers]]

name = "python"
enabled = true
dependency_file_paths = [
  "requirements.txt",
  "athena.toml",
  "tox.ini"
]